name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Model performance
      id: test-model-performance
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Model performance
        setup-command: pip install pytest unittest pandas numpy scikit-learn scipy imbalanced-learn matplotlib seaborn
        command: python -m pytest ex3_test.py::test_model_performance
        timeout: 10
        max-score: 8
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-MODEL-PERFORMANCE_RESULTS: "${{steps.test-model-performance.outputs.result}}"
      with:
        runners: test-model-performance